services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:latest
    container_name: node
    ports:
      - 3000:3000
    volumes:
      - ./app:/home/node/app
    environment:
      - NODE_ENV=development
      - ENTRYPOINT_FILE=helloworld.js
